tests/test_ai/test_priority_algorithm/test_mutations/test_robinhood.py

One test for the robinhood mutation had small, random, chance to fail
Use a starting teamset with only two teams to guarantee that they get chosen
Closes #122

Fix robinhood test

---

api/ai/new/interfaces/algorithm.py
api/ai/new/interfaces/algorithm_config.py
api/ai/new/interfaces/algorithm_options.py
api/ai/new/random_algorithm/random_algorithm.py
api/ai/new/weight_algorithm/weight_algorithm.py

related to #108 
Adds this structure for the reimplementation of the algorithms
Comments in the code specify, but tldr Configs exist so we can augment how algorithms actually behave and they are not something to be customized by end users, but eventually there will be a simple way to overwrite these configs within a simulation for benchmarking purposes

early work for algorithm config support

---

benchmarking/evaluations/graphing/graph_metadata.py
benchmarking/evaluations/graphing/line_graph.py

With the legend subtitle set to "ABC123" for all lines (you are able to have a different one for each line), the line set to be "purple" for the Random algorithm, and the marker set to be "X" for the Weight algorithm
Closes #135 
Closes #136

Add more customizability to graphs

---

api/models/enums.py
benchmarking/data/simulated_data/mock_student_provider.py
benchmarking/simulation/basic_simulation_set.py
benchmarking/simulation/basic_simulation_set_2.py
benchmarking/simulation/mock_algorithm_2.py
benchmarking/simulation/simulation_settings.py
tests/test_benchmarking/test_data/test_simulated_data/test_mock_student_provider.py
tests/test_benchmarking/test_simulation/test_simulation.py
tests/test_utils/test_validation.py
utils/validation.py

closes #125 
tldr; I got greedy and earlier thought I could represent project preferences as just any other attribute - we can't. It's important for many algorithms that we know what the project preferences are.
This PR conclusively makes `Student.project_preferences` *the* way to represent this info
Also included:
- MockStudentProvider can now mock students having preferences (it's more obvious how to do this, too, RE: #101 )
- Adding validations to mock student provider settings
- Adding compatibility validation between initial teams provider and student provider
- Minor improvements to validation utils

add proper project preferences support

---

benchmarking/runs/three_tokenization_constraints.py
benchmarking/simulation/basic_simulation_set.py
benchmarking/simulation/basic_simulation_set_2.py
benchmarking/simulation/insight.py
benchmarking/simulation/simulation.py
benchmarking/simulation/simulation_settings.py
old/team_formation/app/team_generator/algorithm/priority_algorithm/priority_algorithm.py
tests/test_benchmarking/test_runs/test_run.py
tests/test_benchmarking/test_simulation/test_insight.py
tests/test_benchmarking/test_simulation/test_simulation.py

closes #111 
closes #167 
- establishes an `Insight` class for processing the outputs of simulations through the lens of metrics
- kinda just decided simulations will return a tuple so run time information is not lost
- BasicSimulationSet2 (the one not being used yet) now explicitly just runs a loop of `Simulation` (I'm just ignoring the performance of this, but left a comment)
- fixed tests as needed
- small quality of life changes

separate simulation from metric insights

---

api/ai/new/interfaces/algorithm.py
api/ai/new/interfaces/team_generation_options.py
api/models/team/model.py
tests/test_api/test_ai/test_interfaces/test_algorithm.py

closes #168 
- Enforces that TeamShells specified in the initial_teams of team gen options must be unique.
- Medium value, but sometimes matters for logic that each team has a unique id (and generally is important)
- It is predicted to be relevant for API responses that these ids are unique, too
- More strictly enforces name uniqueness too
- Fixed some validation in team gen options (it is okay to give less initial_teams than total_teams, the logic will fill in the teams you don't specify explicitly until we have total_teams)

enforce unique ids on intial teams specifications

---

benchmarking/simulation/basic_simulation_set_2.py
tests/test_benchmarking/test_simulation/test_basic_simulation_set_2.py

closes #174 
- Automatically creates a nested cache folder for each algorithm type it runs for within the base cache key

add cache keys to basic simulation set

---

api/ai/new/interfaces/algorithm_config.py
api/ai/new/priority_algorithm/mutations/__init__.py
api/ai/new/priority_algorithm/mutations/random_swap.py
api/ai/new/priority_algorithm/priority_algorithm.py
tests/test_api/test_ai/test_algorithm_runner.py
tests/test_api/test_ai/test_priority_algorithm/test_priority_algorithm.py

closes #102 
- adds a mutations config to the priority algorithm config
- specifies mutation functions and how many team sets should be mutated this way
- must sync with MAX_SPREAD
- used in the algorithm and tested
- implemented a default for this
NOTE: this kinda means all mutation functions in the future kinda sorta need to take the same params (ish, see what happened to random swap for lore)
Bonus: learned about mocking today :D

add mutation config

---

benchmarking/evaluations/graphing/line_graph.py
benchmarking/evaluations/graphing/line_graph_metadata.py

- Can use `save_graph` attribute of `LineGraphMetadata` to save a graph
- Can use `file_name` attribute of `LineGraphMetadata` to specify the filename for the saved graph, defaults to the graph title
- Also made the `Optional` attributes of `LineGraphMetadata` actually optional by defaulting them to None
Closes #188

Added option to save graphs

---

api/ai/new/priority_algorithm/mutations/robinhood.py
api/ai/new/priority_algorithm/priority/interfaces.py
api/ai/new/priority_algorithm/priority/priority.py
api/ai/new/priority_algorithm/scoring.py
api/ai/priority_algorithm/priority.py
benchmarking/evaluations/metrics/priority_satisfaction.py
benchmarking/simulation/goal_to_priority.py
tests/test_api/test_ai/test_priority_algorithm/test_mutations/test_local_max.py
tests/test_api/test_ai/test_priority_algorithm/test_mutations/test_util.py
tests/test_benchmarking/test_simulation/test_goal_to_priority.py

closes #204 
- Adds regular diversification/concentration priorities
- implemented into the algorithm runner so it'll auto convert
- The thing to note here is that Priority subclasses will now have a `def satisfaction() -> float` instead of a `def satisfied_by() -> bool`. This is because the logic actually works essentially the same with minor modifications and then allows the question "does this group of students satisfy this priority" to be more like "how much does this team of students satisfy this priority"

implement diversity priority without tokenization [204]

---

api/ai/priority_algorithm/priority/priority.py
tests/test_api/test_ai/test_priority_algorithm/test_priority/test_priority.py

closes #223
Tokenization priority is no longer a binary check. This change allows the nuance of generally still caring about diversity of teams, but putting extra focus on not tokenizing students.

improve tokenization priority

---

api/ai/priority_algorithm/priority/priority.py
api/ai/priority_algorithm/priority_algorithm.py
api/models/team/model.py
benchmarking/evaluations/metrics/priority_satisfaction.py
benchmarking/runs/diversify_gender_min_2.py
benchmarking/runs/three_tokenization_constraints.py
benchmarking/simulation/goal_to_priority.py
benchmarking/simulation/simulation.py
tests/test_api/test_ai/test_priority_algorithm/test_priority/test_priority.py
utils/visibility.py

Changes
- added a small util for displaying team set overviews and marking students based on any criteria you want
- fully resolved the switch to using team shells for priority teams (proper conversion back and forth)
- made `goal_to_priority()` dynamically handle new support to priorities

utils for displaying team sets

---

benchmarking/evaluations/goals.py
benchmarking/simulation/goal_to_priority.py
benchmarking/simulation/mock_algorithm.py

Unnecessary, if you don't want a requirement goal to match skills then you simply wouldn't include a requirement goal

remove match_skills from requirement priority

---

benchmarking/data/simulated_data/mock_student_provider.py
tests/test_benchmarking/test_data/test_simulated_data/test_mock_student_provider.py

Closes #232 
Description in issue. Reasoning for fix is that since specifying 2 enemies creates two enemy relationships on each student, specifying 2 friends should also do the same. The old behaviour is that each student would be a part of a clique of 2, rather than have 2 friends

mock student generator bug fix

---

benchmarking/evaluations/graphing/line_graph.py

If you try to use `save_graph = True` and provide a `file_name` that contains a folder that doesn't exist, it crashes
Closes #243

Fix graphing tool not creating driectory where it wants to save the graph

---

benchmarking/runs/social/varied_class_size.py
benchmarking/runs/social/varied_num_enemies.py

I done goofed this one, silly mistake. It was intended for the clique size to be equal to the team size, which is 5 for these two runs
Closes #266

Use the correct number of friends for social runs

---

benchmarking/simulation/mock_algorithm.py

The social algorithm finds cliques of students up to a clique size of `max_team_size`. The problem is that `max_team_size` is not being calculated correctly. It assumed that `num_students` is not evenly divisible by `num_teams`. The result is that `max_team_size` is one too big in the case that it is evenly divisible and social was finding cliques that were too big.
Closes #264

Fix calculation of max_team_size

---

api/ai/priority_algorithm/priority/priority.py

Quick bug - the `* 2` was not supposed to be there, and the condition for num students is unneeded now that the max friends and enemies are explicitly specified

fix social preference priority satisfaction

---

api/api/utils/response_with_metadata.py
api/api/views/generate_teams.py

Currently, we only return 500 when there is an error when validating the schema. We should catch the specific error and send that to the error.
Minor fix: we always have teams as the data label, so I replaced "data" with "teams"
Sample error message:
```json
{
"teams": null,
"metadata": {
"version": "v0.1.0",
"timestamp": 1702550314.0737631
},
"error": "Student 1 has project preferences that do not exist in the project set."
}
```

Fix API not response with a correct error message

---

benchmarking/data/simulated_data/mock_student_provider.py

- `self.attribute_ranges` has the type `Dict[int, AttributeRangeConfig]` but this is checking `self.attribute_ranges[0]`, which might not exist. We can move this down inside of the loop.
- `total_chance` is a float, so should compare with margin of error

Fix MockStudentProvider validation

---

benchmarking/evaluations/goals.py
benchmarking/simulation/goal_to_priority.py

Fix bugs from #334 
From Discord message:
> I got `{'PrioritySatisfaction': {'AlgorithmType.PRIORITY-PriorityAlgorithm': 1.0833333333333333}}`
This is caused by always defaulting max_num_choices to 1.

Fix Priority Algorithm's internal scoring function for concentration

---

benchmarking/evaluations/metrics/utils/student_calculations.py

`num_enemies_satisfied` returns the number of enemies that were successfully kept out of the student's team, not the number of enemies in the team, so the logic was wrong.
Closes #359

Fix bug in new social metric

---

benchmarking/evaluations/metrics/cosine_similarity.py

This is a solution to the problem, but I'm open to other solutions. I think Seth is right with this as the solution because a student with a zero vector should be considered completely different from every other student, hence a return of 0. Other solutions online suggest using a small epsilon in the equation like `dot(v1, v2)/max(norm(v1)*norm(v2), epsilon)`, but this would cause a large value for the cosine similarity which, not only doesn't make sense in our use case, but also messes with the whole "returns a number in [0,1]"
Closes #362

Fix divide by zero error in cosine similarity

---

benchmarking/evaluations/metrics/cosine_similarity.py
tests/test_benchmarking/test_evaluations/test_metrics/test_cosine_similarity.py

We would like to be able to measure the cosine similarity/difference of students on a filtered list of attributes. This is specifically useful in the case where we are using students with many more attributes/skills than we care about diversifying. Often we only want to measure that gender and race were diversified, and don't care about which framework they know and so don't want that affecting the score.
Closes #357

Allow filtering of cosine similarity to specific attributes
