algorithm_sandbox/mock_team_generation.py
algorithm_sandbox/util.py
team_formation/app/team_generator/algorithm/algorithms.py
team_formation/app/team_generator/algorithm/priority_algorithm/priority.py
team_formation/app/team_generator/algorithm/priority_algorithm/priority_algorithm.py
team_formation/app/team_generator/algorithm/priority_algorithm/priority_teamset.py
team_formation/app/team_generator/team.py
test_priority.py

+ add priority algorithm
Closes #16

Add priority algorithm

---

team_formation/app/team_generator/algorithm/social_algorithm/social_algorithm.py
team_formation/app/team_generator/team.py

+ add support for assigning socially generated teams to projects according to project preference
Closes #13

Support project preferences

---

algorithm_sandbox/visualization/README.md
algorithm_sandbox/visualization/visualize_logs.py
algorithm_sandbox/visualization/visualize_teams.py

toggle display all edge, friends only, enemies only

now edge dropdown functionality is added

---

METRICS.md
README.md
restructure/simulations/data/interfaces.py
restructure/simulations/data/simulated_data/mock_student_provider.py
restructure/simulations/runs/test_saved_run.py
restructure/tests/test_simulations/test_data/test_simulated_data/test_mock_student_provider.py

add support for multi-value attributes

---

benchmarking/data/README.md

Extra documentation for this provider's settings

doc mock student provider settings

---

README.md
benchmarking/runs/CONVENTION.md
benchmarking/runs/test_saved_run.py

- Added python version to readme
- Added main function to test_saved_run
- Added requirement to convention that test files must have a main function

Add Python Version to Readme and Main to Run test_saved_run

---

benchmarking/evaluations/metrics/average_gini_index_multi_attribute.py
benchmarking/evaluations/scenarios/concentrate_all_attributes.py
benchmarking/runs/run_concentrate_all_attributes.py
models/enums.py

Create a simulation of  scenario that tries to create groups where people with similar attributes are grouped together
- Added new variation of `AverageGiniIndex` class, `AverageGiniIndexMultiAttribute`, to avg across a list of attributes rather than just a single attribute
- Added scenario `ConcentrateAllAttributes` that tries to concentrate the age, gender, gpa, race, major, and year level attributes of a team
- Added a run to test the scenario
The output seems to be close to Figure 10 of Keyvon's paper, so I hope what I have is at least on the right track, but I'm sure that there are a couple details that I didn't get right. In particular, I'm not sure that I created the scenario correctly by listing all 6 goals and then the `WeightGoal`. And I'm also not sure if what I've done with …

Create run to concentrate on all attributes

---

benchmarking/evaluations/metrics/maximum_gini_index.py
benchmarking/evaluations/metrics/minimum_gini_index.py
benchmarking/evaluations/scenarios/concentrate_gpa.py
benchmarking/runs/concentrate_gpa_run.py

- Added a metric to calculate and the minimum gini index across all of the teams
- Added a metric to calculate and the maximum gini index across all of the teams
- Added a scenario to form teams just by focusing on concentrating individuals on teams with similar GPA
- Added a run for the concentrate on GPA scenario

Create Scenario Run to Concentrate on GPA

---

ai/priority_algorithm/mutations.py
ai/priority_algorithm/priority.py
ai/priority_algorithm/priority_algorithm.py
ai/priority_algorithm/priority_teamset.py
ai/priority_algorithm/scoring.py
models/team.py

make priority mutations static

---

ai/priority_algorithm/interfaces.py
ai/priority_algorithm/priority.py
ai/priority_algorithm/priority_algorithm.py
ai/priority_algorithm/priority_teamset.py
ai/priority_algorithm/scoring.py
benchmarking/evaluations/goals.py
benchmarking/evaluations/interfaces.py
benchmarking/evaluations/metrics/utils/student_calculations.py
benchmarking/evaluations/metrics/utils/team_calculations.py
benchmarking/evaluations/scenarios/diversify_gender_min_2_female.py
benchmarking/runs/test_saved_run.py
benchmarking/simulation/algorithm_translator.py
benchmarking/simulation/mock_algorithm.py
models/enums.py
models/project.py
models/student.py
models/team.py
models/tokenization_constraint.py
old/team_formation/app/team_generator/algorithm/priority_algorithm/scoring.py

coerce priority algorithm to current models

---

benchmarking/simulation/simulation.py
tests/test_benchmarking/test_simulation/test_simulation.py

support specifying which algorithms to run with

---

benchmarking/runs/diversify_gender_min_2.py

Added a run for the diversify gender with min of two scenarios to benchmark the priority algorithm.

Create Run for Diversify Gender Min 2

---

benchmarking/data/interfaces.py
benchmarking/data/simulated_data/mock_initial_teams_provider.py
benchmarking/data/simulated_data/mock_student_provider.py
benchmarking/runs/concentrate_gpa.py
benchmarking/runs/concentrate_many_attributes.py
benchmarking/runs/include_social_friends.py
models/project.py
models/team.py
tests/test_benchmarking/test_data/test_simulated_data/test_mock_initial_teams_provider.py
tests/test_benchmarking/test_data/test_simulated_data/test_mock_student_provider.py
tests/test_benchmarking/test_simulation/test_simulation.py
tests/test_utils/test_validation.py
utils/validation.py

mock initial teams provider

---

ai/priority_algorithm/mutations.py
ai/priority_algorithm/mutations/random.py
ai/priority_algorithm/mutations/robinhood.py
ai/priority_algorithm/mutations/utils.py
ai/priority_algorithm/priority_algorithm.py
benchmarking/runs/test_saved_run.py
tests/test_ai/test_priority_algorithm/test_mutations.py
tests/test_ai/test_priority_algorithm/test_mutations/test_robinhood.py

- Implement the "Robinhood" mutation method
- Swaps students between a team that satisfies a constraint and a team that does not
- See #76 for more
Closes #76

Create Robinhood mutation method for priority algorithm

---

ai/new/interfaces/algorithm_options.py

Partially resolves an issue with validation. Need to determine what to do with PriorityAlgorithmOptions at a later date.

Added validation for WeightAlgorithmOptions.

---

api/ai/new/interfaces/algorithm.py
api/ai/new/interfaces/algorithm_config.py
api/ai/new/interfaces/algorithm_options.py
api/ai/new/priority_algorithm/interfaces.py
api/ai/new/priority_algorithm/mutations/local_max.py
api/ai/new/priority_algorithm/mutations/random_swap.py
api/ai/new/priority_algorithm/mutations/robinhood.py
api/ai/new/priority_algorithm/mutations/utils.py
api/ai/new/priority_algorithm/priority.py
api/ai/new/priority_algorithm/priority_algorithm.py
api/ai/new/priority_algorithm/priority_teamset.py
api/ai/new/priority_algorithm/scoring.py
api/ai/runner.py
old/team_formation/app/team_generator/algorithm/utility/social_network.py

adding priority to the newer structure, early prep for what the algorithm runner will look like

revamp priority algorithm and runner

---

tests/test_api/test_ai/test_priority_algorithm/test_mutations/test_util.py
tests/test_utils/test_dictionaries.py
utils/dictionaries.py

little util needed for something else

prune dictionaries util

---

benchmarking/runs/concentrate_gpa.py
benchmarking/runs/concentrate_many_attributes.py
benchmarking/runs/diversify_gender_min_2.py
benchmarking/runs/include_social_friends.py
benchmarking/runs/three_tokenization_constraints.py
benchmarking/simulation/basic_simulation_set.py
benchmarking/simulation/basic_simulation_set_2.py
benchmarking/simulation/mock_algorithm_2.py
tests/test_benchmarking/test_simulation/test_basic_simulation_set.py

Makes more sense for this to be called BasicSimulationSet since it runs multiple algorithms at the same time
See the branch stacked on top of this for why this happened

basic simulation set rename

---

benchmarking/simulation/basic_simulation_set.py
benchmarking/simulation/simulation.py
benchmarking/simulation/simulation_settings.py
tests/test_benchmarking/test_simulation/_data.py
tests/test_benchmarking/test_simulation/test_basic_simulation_set.py
tests/test_benchmarking/test_simulation/test_simulation.py

- creates a class to run a single algorithm at a time (will soon include the support to pass a custom algorithm config)
- testing for this
- created SimulationSettings that this new Simulation class uses (will later switch BasicSimulationSet to use this)
- moved shared data in test directory to a `_data.py` file

create singular simulation class

---

benchmarking/simulation/simulation.py
tests/test_benchmarking/test_simulation/test_simulation.py

support custom configs on Simulation

---

benchmarking/caching/simulation_cache.py
tests/test_benchmarking/test_caching/test_simulation_cache.py

- Actually not much, just make sure the directory is created and normalize path
Closes #170

Nested cache directories

---

benchmarking/simulation/simulation.py
tests/test_benchmarking/test_simulation/test_simulation.py

`Simulation` loads the cache and checks if it needs to continue doing runs. If not, it will just return the cached runs
Closes #169

Continue cached simulations

---

benchmarking/evaluations/graphing/line_graph_metadata.py
benchmarking/runs/concentrate_gpa.py
benchmarking/runs/concentrate_many_attributes.py
benchmarking/runs/diversify_gender_min_2.py
benchmarking/runs/include_social_friends.py
benchmarking/runs/three_tokenization_constraints.py

- changed all runs to use new simulation set
- also added default to line graph settings

Fix Runs With Cashing

---

api/ai/new/priority_algorithm/mutations/robinhood.py
utils/validation.py

Minor fix I ran into when making a custom student provider

fix validation on assert can exist together

---

api/models/team/model.py
api/models/team/serializer.py
tests/test_api/test_models/test_team/test_serializer.py
utils/testing.py

closes #185
See #196, tests will be written for `teams_are_equal` soon™️

students should have their team set when decoded

---

api/ai/new/priority_algorithm/mutations/local_max.py
tests/test_api/test_ai/test_priority_algorithm/test_mutations/test_local_max.py

- implemented local max random mutation

Implement Local Max Random Mutation

---

benchmarking/runs/concentrate_gpa.py
benchmarking/runs/concentrate_many_attributes.py
benchmarking/runs/diversify_gender_min_2.py
benchmarking/runs/include_social_friends.py
benchmarking/runs/interfaces.py
benchmarking/runs/three_tokenization_constraints.py

Additions
- runs have been migrated into a class-based structure
- this ensures the defaults for the `start` method's parameters are consistent
- this also provides the benefit of a class structure we can add further defaults and helper functions to

switch runs to class structure

---

api/ai/algorithm_runner.py

closes #224 
The lore is in the issue description

fix weight algorithm score inflation [224]

---

api/ai/priority_algorithm/priority/priority.py
benchmarking/evaluations/goals.py
benchmarking/simulation/goal_to_priority.py
tests/test_api/test_ai/test_priority_algorithm/test_priority/test_priority.py

closes #214 
- adds project preference priority
- tests for that
- added to goal_to_priority

project preference priority [214]

---

benchmarking/evaluations/metrics/utils/student_calculations.py

Fixed bug related to student friend/enemies not being counted correctly

---

api/models/enums.py
benchmarking/evaluations/goals.py
benchmarking/evaluations/scenarios/project_location.py
benchmarking/evaluations/scenarios/project_requirement_preferences_diversify_gender.py

- made some new more complex scenarios to benchmark the priority algorithm with

Create New Scenarios to Benchmark Priority

---

benchmarking/evaluations/graphing/line_graph.py

Close plot after showing or saving

---

benchmarking/evaluations/scenarios/give_the_people_what_they_want.py
benchmarking/runs/social/scoial_run.py
benchmarking/runs/social/varied_class_size.py
benchmarking/runs/social/varied_num_enemies.py
benchmarking/runs/social/varied_num_friends.py
benchmarking/runs/social/varied_team_size.py

Benchmark social algorithm while varying
- Team size
- Num friends/enemies
- Student relationship type (clustered friendships, non-mutual friendships)
Closes #219

Benchmark social algorithm with different parameters

---

benchmarking/evaluations/scenarios/include_friends_exclude_enemies.py
benchmarking/runs/social/varied_class_size.py
benchmarking/runs/social/varied_num_enemies.py
benchmarking/runs/social/varied_num_friends.py
benchmarking/runs/social/varied_team_size.py

RIP GiveThePeopleWhatTheyWant

---

api/ai/interfaces/algorithm_options.py
api/ai/priority_algorithm/priority/interfaces.py
api/ai/priority_algorithm/priority/priority.py
api/models/enums.py
tests/test_api/test_ai/test_priority_algorithm/test_mutations/test_local_max.py
tests/test_api/test_ai/test_priority_algorithm/test_mutations/test_robinhood.py

Add priority validation

---

benchmarking/caching/simulation_cache.py
benchmarking/caching/utils.py
benchmarking/simulation/utils.py
tests/test_benchmarking/test_caching/_data.py
tests/test_benchmarking/test_caching/test_simulation_cache.py
tests/test_benchmarking/test_caching/test_utils.py
tests/test_benchmarking/test_simulation/test_utils.py

Write chunk() and combine() functions

---

benchmarking/runs/social/varied_class_size.py
benchmarking/runs/social/varied_num_enemies.py
benchmarking/runs/social/varied_num_friends.py
benchmarking/runs/social/varied_team_size.py

Refactor out old scenario name

---

api/ai/priority_algorithm/priority/priority.py
tests/test_api/test_ai/test_priority_algorithm/test_priority/_data.py
tests/test_api/test_ai/test_priority_algorithm/test_priority/test_priority.py
utils/math.py

implement social priority [213]

---

api/api/utils/generate_teams_data_loader.py
api/models/student/serializer.py
api/models/team/serializer.py
api/models/team_set/serializer.py

Use serializers in api data loader

---

benchmarking/runs/concentrate_gpa.py
benchmarking/runs/concentrate_many_attributes.py
benchmarking/runs/diversify_gender_min_2.py
benchmarking/runs/include_social_friends.py
benchmarking/runs/interfaces.py
benchmarking/runs/social/scoial_run.py
benchmarking/runs/social/varied_class_size.py
benchmarking/runs/social/varied_num_enemies.py
benchmarking/runs/social/varied_num_friends.py
benchmarking/runs/social/varied_team_size.py
benchmarking/runs/three_tokenization_constraints.py

- refactored run start method to not be static

Change Run Class Start Method to be Non-Static

---

benchmarking/runs/priority_algorithm/diversify_gender_min_2_lower_priority_constants/class_size.py
benchmarking/runs/priority_algorithm/diversify_gender_min_2_lower_priority_constants/interfaces.py
benchmarking/runs/priority_algorithm/diversify_gender_min_2_lower_priority_constants/max_keep.py
benchmarking/runs/priority_algorithm/diversify_gender_min_2_lower_priority_constants/max_spread.py
benchmarking/runs/priority_algorithm/diversify_gender_min_2_lower_priority_constants/max_time.py
benchmarking/runs/priority_algorithm/diversify_gender_min_2_lower_priority_constants/num_iterations.py

- reduced the priority algorithm constants to see if they are more independent

Run Diversify Gender Min 2 Scenario with Lower Priority Algorithm Constants

---

benchmarking/caching/simulation_cache.py
benchmarking/caching/utils.py
benchmarking/runs/concentrate_gpa.py
benchmarking/simulation/simulation.py
benchmarking/simulation/simulation_set.py

Use the same set of students within same trial

---

benchmarking/data/simulated_data/mock_student_provider.py
tests/test_benchmarking/test_data/test_simulated_data/test_mock_student_provider.py

student provider randomly seeded

---

api/ai/priority_algorithm/priority/priority.py
tests/test_api/test_ai/test_priority_algorithm/test_priority/test_priority.py
utils/math.py

rework tokenization priority satisfaction

---

requirements.txt

Added Library to Query JSON

---

benchmarking/evaluations/metrics/priority_satisfaction.py

- added an option for the exponent base in the priority satisfaction metric

Add Option For Exponent Base in Priority Satisfaction Metric

---

utils/query.py

- counts the number of students on each team who have a certain attribute
- returns a list of lists where the outer list has length `num_trials` and the inner list length is the number of teams in the `team_set` file

Create Function to Count the Number of Students with a Certain Attribute

---

benchmarking/evaluations/goals.py
benchmarking/simulation/goal_to_priority.py

Fix social priority goal conversion

---

api/ai/interfaces/algorithm_config.py
api/ai/priority_algorithm/priority_algorithm.py
api/models/enums.py
benchmarking/evaluations/graphing/graph_3d.py
benchmarking/evaluations/scenarios/include_social_friends.py

We're getting greedy here, lets move some of these good changes to main so other branches can use them
Closes #337

Some changes from the MEGA BRANCH ʷᵒᵒᵒ that should be in main

---

benchmarking/data/simulated_data/mock_student_provider.py
benchmarking/evaluations/metrics/cosine_similarity.py
tests/test_benchmarking/test_evaluations/test_metrics/test_cosine_similarity.py

Write cosine similarity metric

---

benchmarking/evaluations/metrics/cosine_similarity.py

Fix cosine similarity

---

benchmarking/evaluations/metrics/priority_satisfaction.py
tests/test_benchmarking/test_evaluations/test_metrics/test_priority_satisfaction.py

- added standard deviation to priority satisfaction

Added Standard Deviation to Priority Satisfaction

---

benchmarking/evaluations/metrics/utils/student_calculations.py
benchmarking/evaluations/metrics/utils/team_calculations.py

Adds new social metric that checks that all students in a team have at least one friend in their team (if they requested friends) and that they have no enemies in their team
Closes #348

Add new social metric

---

benchmarking/evaluations/metrics/average_social_satisfied.py

Simple addition to help get the stdev of social satisfaction among teams
Closes #355

Add stdev of social satisfaction among teams

---

benchmarking/data/simulated_data/mock_student_provider.py
benchmarking/evaluations/goals.py
tests/test_benchmarking/test_data/test_simulated_data/test_mock_student_provider.py

Fixing the random_choice issue
Cascaded into ensuring this change still works for generating attribute values
Added tests both for visibility on this issue and for visibility into attribute value generation that it fed into

fix random_choice size defaults

---

api/models/student/serializer.py
api/models/team/serializer.py
api/models/team_set/serializer.py
tests/test_api/test_models/test_student/test_serializer.py
tests/test_api/test_models/test_team/test_serializer.py
tests/test_api/test_models/test_team_set/test_serializer.py

Serializer should use id instead of _id

---

benchmarking/data/real_data/cosc341_w2021_t2_provider/get_statistics.py

- added file used to generate COSC 341 population statistics for paper

Add File Used to Generate COSC 341 Population Statistics

---

README.md

The `--recursive` isn't strictly necessary, but may as well be there
Closes #383

Update docs to include submodule initialization

---

api/ai/double_round_robin_algorithm/double_round_robin_algorithm.py

DRR has a fixed length now, but the result can be less than the predefined length.
Branched out from #331

Adjustable length for DRR

---

api/ai/interfaces/algorithm_config.py

Currently just a field and never got passed in
Branched out from #331

Fix algorithm configs for algorithms needing utility_function

---

api/ai/priority_algorithm/mutations/team_size_low_disruption.py
tests/test_api/test_ai/test_priority_algorithm/test_mutations/test_team_size_low_disruption.py

Add team size mutation that minimizes team disruption

---

benchmarking/simulation/mock_algorithm.py

- There was an issue with the group matcher implementation within our repo, and group matcher does currently not run.
- This is a minor fix to remedy that.

Fix Group Matcher Crashing
